#!/bin/bash

#--------------------------------------------------------------------------
# GRVY Test Suite
#
# Test standalone binaries
# --------------------------------------------------------------------------

EXE=../src/hostinfo
TEST_FILE=.hostinfo

# Compiled binaries must exist

if test ! -x $EXE ; then
    echo "${0}: Expected binary does not exist or is not executable"
    exit 1
fi

$EXE > $TEST_FILE 2> /dev/null || exit 1
#$EXE > $TEST_FILE || exit 1

# Verify we have expected output files

if test ! -s $TEST_FILE ; then
    exit 1
fi

# Let's at least check that we got the hostname right

HOST1=`cat $TEST_FILE | head -1 | awk '{print $3}' | awk -F '.' '{print $1}'`
HOST2=`hostname -s`

if test "$HOST1" != "$HOST2" ;then
    echo "${0}: Hostname mismatch"
    exit 1	 
fi

# Clean up

if test -e $TEST_FILE ; then
   rm -f $TEST_FILE
fi

exit 0



