#! /bin/sh
# --------------------------------------------------------------------------
# bootstrapping utility for autotools -> now just uses autreconf
#
# $Id: bootstrap 469 2008-09-05 00:16:18Z rhys $
# -------------------------------------------------------------------------- 

cmd="autoreconf -f -i"
echo "Bootstrapping using $cmd ..."

$cmd


