# Simple 1st cut build for HPCT library

.SUFFIXES: .o .c .f .f90 .cpp .a



HPCT_LIB=libhpct.a
INCLUDES=GetPot
INCLUDEDIRS=-I ./
CCOMP=g++
CFLAGS=-g -O1
UNAME=$(shell uname)
LIBMDLS = $(HPCT_LIB)(hpct_input.o) 

$(HPCT_LIB): $(LIBMDLS)
$(LIBMDLS): $(INCLUDES)

.cpp.a: 
	$(CCOMP) -c $(CFLAGS) $(INCLUDEDIRS) $<
	ar -rv $@ $*.o
	rm -f $*.o

clean:
	rm -f $(HPCT_LIB)