name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Boost/Autotools
        run:  sudo apt-get install libboost-dev autoconf automake libtool
      - name: Bootstrap
        run:  ./bootstrap
      - name: Configure
        run:  ./configure --enable-boost-headers-only CXXFLAGS="-fdiagnostics-color=always" CFLAGS="-fdiagnostics-color=always"
      - name: Make
        run:  make -j 2
      - name: Test
        run:  make AM_COLOR_TESTS=always -j 2 check
