name: Doxygen docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Doxygen 
        uses: sudo apt-get install doxygen
      - name: Install Boost/Autotools
        run:  sudo apt-get install libboost-dev autoconf automake libtool
      - name: Bootstrap
        run:  ./bootstrap
      - name: Configure
        run:  ./configure --enable-boost-headers-only
      - name: Build docs
        run:  make doc

